### ISSUE TITLE
[BUG] - Year heeft geen correcte validatie op verkeerd input

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-pattern#14]
**Omschrijf het probleem**
Bij het gebruik van vl-ui-pattern, krijgt datepicker geen validatiefouten wanneer de input verkeerd is. (dag/maand lijkt wel ok)

**Hoe te reproduceren**
Invullen van "31.12.0000" of "31.12.123" of "31.12.124141415" of "31.12.201" ...

**Comment by coemans** [comment]
We zouden `31.12.0000` inderdaad kunnen toevoegen als invalid date. De andere datums worden in de huidige versie omgevormd:

`31.12.123` naar `31.12.2021`
`31.12.124141415` naar `31.12.1241` bij copy paste want manueel input van in combinatie met pattern is niet mogelijk
`31.12.201` naar `31.12.2021` maar lijkt me identiek aan `31.12.123`

Ticket blijft open voor `31.12.0000` al kan in de tussentijd het attribuut `data-vl-min-date` gebruikt worden om dit probleem te voorkomen.
