### ISSUE TITLE
[BUG] - Gekopieerde waarde blijft ongeldig

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-pattern#2]
**Omschrijf het probleem**
Dit gebeurt in combinatie met vl-ui-form-validation:

```HTML
<label` is="vl-form-label" for="insz-input" block>${translate('registratie.insz.INSZ')}</label>
            <input id="insz-input" is='vl-input-field' block data-required="true"
                            @input="${this._onInszInputChanged}"
                            type="text"
                            placeholder="11.22.33-444.55"
                            data-vl-validation-type="rrn"
                            data-vl-pattern="rrn"
                            data-vl-error-message="${translate('registratie.insz.input-error')}"
                            data-vl-error-placeholder="validation-insz-error"/>
             <p id="insz-input-validation-message" is="vl-form-validation-message" error `data-vl-error-id="validation-insz-error"></p>
```

vb:
Als ik  "78481219363" in de input plakken, de waard is well geformatteerd maar de niet geldig.
<img width="660" alt="Screenshot 2020-07-01 at 18 38 40" src="https://user-images.githubusercontent.com/51441000/86269522-26628480-bbca-11ea-9ca3-376ca0f795f8.png">

**Comment by coemans** [comment]
@ZhaodiFengVlaanderen het probleem wordt veroorzaakt door de logica die onmiddellijk uitgevoerd wordt op het input event. De vl-ui-pattern logica gaat de value wijzigen, maar jullie logica gaat al aangeroepen worden voordat de vl-ui-pattern het patroon heeft kunnen wijzigen. Een mogelijke oplossing is de logica achteraan op de chain zetten door `setTimeout` te gebruiken of het change event te gebruiken. Het change event wordt wel pas bij unfocus aangeroepen.

**Comment by ZhaodiFengVlaanderen** [comment]
@coemans, voor enkel edge case is dit probleem toch niet opgelost...

Ik krijgt dit probleem nog altijd in de developer mode van chrome en chrome mobile. 

Voor onze project is dit ok. Hier is puur voor informeren.
