### ISSUE TITLE
[TASK] - documentatie 'data-vl-numerical-decimal-scale' lijkt incorrect

### ISSUE THREAD

**Issue by stefanborghys** [milieuinfo/webcomponent-vl-ui-pattern#28]
**Beschrijving**
Zag voor de 'data-vl-numerical-decimal-scale' attribuut volgende in de documentatie:
![vlPattern](https://user-images.githubusercontent.com/1375279/115401340-93dbb200-a1ea-11eb-90c7-cc667fb8bc2c.png)

Als ik de code bekijk zit het daar vermodelijk bewust zo toegevoegd.
![afbeelding](https://user-images.githubusercontent.com/1375279/115401445-b1108080-a1ea-11eb-80bb-1e97fa82afe7.png)

**Comment by coemans** [comment]
De JSDoc syntax is inderdaad verkeerd, kan best aangepast worden.
